import React, { useState, useEffect } from 'react';
import { getPatientRecords } from '../../services/medicalService';
import { useAuth } from '../../context/AuthContext';

const DEMO_RECORDS = [
  {
    _id: 'r1',
    visitDate: '2024-01-10T00:00:00Z',
    doctorName: 'Dr. Anita Roy',
    diagnosis: 'Upper Respiratory Infection',
    visitNotes: 'Patient had sore throat and mild fever for 3 days.',
    prescriptions: [
      { medicine: 'Azithromycin 500mg', dosage: '1 tablet once daily for 3 days' },
      { medicine: 'Paracetamol 650mg', dosage: '1 tablet thrice daily for 5 days' },
    ],
  },
  {
    _id: 'r2',
    visitDate: '2023-12-20T00:00:00Z',
    doctorName: 'Dr. Rakesh Mehta',
    diagnosis: 'Hypertension Management',
    visitNotes: 'BP was 140/90. Prescribed lifestyle changes and medication.',
    prescriptions: [
      { medicine: 'Amlodipine 5mg', dosage: '1 tablet once daily (morning)' },
    ],
  },
];

const MyRecords = () => {
  const { user } = useAuth();
  const [records, setRecords] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedRecord, setSelectedRecord] = useState(null);

  useEffect(() => {
    const load = async () => {
      try {
        const res = await getPatientRecords(user?._id || user?.id);
        setRecords(res.data.records || res.data || DEMO_RECORDS);
      } catch {
        setRecords(DEMO_RECORDS);
      }
      setLoading(false);
    };
    load();
  }, [user]);

  // EXTRA FEATURE - Download prescription as .txt file
  const downloadPrescription = (record) => {
    const content = [
      '==============================',
      '       MEDICAL PRESCRIPTION',
      '==============================',
      `Date       : ${new Date(record.visitDate).toLocaleDateString()}`,
      `Doctor     : ${record.doctorName}`,
      `Diagnosis  : ${record.diagnosis}`,
      '',
      'PRESCRIBED MEDICINES:',
      '----------------------',
      ...record.prescriptions.map((p, i) => `${i + 1}. ${p.medicine}\n   Dosage: ${p.dosage}`),
      '',
      'VISIT NOTES:',
      '------------',
      record.visitNotes,
      '',
      '==============================',
      'Generated by HealthCare Pro',
      `Patient: ${user?.name || 'Patient'}`,
      '==============================',
    ].join('\n');

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `prescription_${record.doctorName.replace(/\s+/g, '_')}_${new Date(record.visitDate).toLocaleDateString('en-GB').replace(/\//g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (loading) return <div className="spinner" style={{ margin: '40px auto' }} />;

  return (
    <div>
      <h1 className="page-title">📁 My Medical Records</h1>

      {records.length === 0 ? (
        <div className="card" style={{ textAlign: 'center', padding: '48px' }}>
          <div style={{ fontSize: '48px', marginBottom: '12px' }}>📄</div>
          <p style={{ color: 'var(--text-secondary)' }}>No medical records found.</p>
          <p style={{ fontSize: '13px', color: 'var(--text-secondary)', marginTop: '8px' }}>
            Records will appear here after your first consultation.
          </p>
        </div>
      ) : (
        records.map((rec) => (
          <div key={rec._id} className="card fade-in">
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
              <div>
                <div style={{ fontWeight: '700', fontSize: '16px', marginBottom: '4px' }}>{rec.diagnosis}</div>
                <div style={{ fontSize: '13px', color: 'var(--text-secondary)' }}>
                  👨‍⚕️ {rec.doctorName} &nbsp;|&nbsp; 📅 {new Date(rec.visitDate).toLocaleDateString()}
                </div>
              </div>
              <div style={{ display: 'flex', gap: '6px' }}>
                <button
                  className="btn btn-outline btn-sm"
                  onClick={() => setSelectedRecord(selectedRecord?._id === rec._id ? null : rec)}
                >
                  {selectedRecord?._id === rec._id ? '▲ Hide' : '▼ View'}
                </button>
                {rec.prescriptions?.length > 0 && (
                  <button
                    className="btn btn-primary btn-sm"
                    onClick={() => downloadPrescription(rec)}
                    title="Download prescription as text file"
                  >
                    ⬇️ Prescription
                  </button>
                )}
              </div>
            </div>

            {selectedRecord?._id === rec._id && (
              <div style={{ marginTop: '16px', paddingTop: '16px', borderTop: '1px solid var(--border)' }} className="fade-in">
                <div style={{ marginBottom: '12px' }}>
                  <strong>Visit Notes:</strong>
                  <p style={{ marginTop: '4px', fontSize: '14px', color: 'var(--text)', lineHeight: 1.6 }}>
                    {rec.visitNotes}
                  </p>
                </div>

                {rec.prescriptions?.length > 0 && (
                  <div>
                    <strong>💊 Prescriptions:</strong>
                    <div style={{ marginTop: '8px', background: 'var(--bg)', padding: '12px', borderRadius: '8px' }}>
                      {rec.prescriptions.map((p, i) => (
                        <div key={i} style={{ padding: '6px 0', borderBottom: i < rec.prescriptions.length - 1 ? '1px solid var(--border)' : 'none' }}>
                          <span style={{ fontWeight: '600', color: 'var(--primary)' }}>{p.medicine}</span>
                          <span style={{ fontSize: '13px', color: 'var(--text-secondary)', marginLeft: '8px' }}>
                            — {p.dosage}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
        ))
      )}
    </div>
  );
};

export default MyRecords;
