import React, { useState } from 'react';
import { getPatientRecords, createRecord, addPrescription } from '../../services/medicalService';

const DEMO_RECORDS = [
  {
    _id: 'r1', visitDate: '2024-01-10', diagnosis: 'Upper Respiratory Infection',
    visitNotes: 'Patient complained of sore throat and runny nose for 3 days.',
    prescriptions: [
      { medicine: 'Azithromycin 500mg', dosage: '1 tablet once daily for 3 days' },
      { medicine: 'Paracetamol 650mg', dosage: '1 tablet thrice daily for 5 days' },
    ],
  },
];

const PatientRecords = () => {
  const [searchQuery, setSearchQuery] = useState('');
  const [records, setRecords] = useState([]);
  const [loading, setLoading] = useState(false);
  const [searched, setSearched] = useState(false);
  const [selectedRecord, setSelectedRecord] = useState(null);
  const [showNewVisit, setShowNewVisit] = useState(false);
  const [patientInfo, setPatientInfo] = useState(null);

  const [newVisit, setNewVisit] = useState({
    visitNotes: '', diagnosis: '', prescriptions: [{ medicine: '', dosage: '' }],
  });

  const handleSearch = async () => {
    if (!searchQuery.trim()) return;
    setLoading(true);
    setSearched(true);
    try {
      const res = await getPatientRecords(searchQuery);
      setRecords(res.data.records || res.data || DEMO_RECORDS);
      setPatientInfo(res.data.patient || { name: searchQuery, id: `P${Math.floor(Math.random() * 9000 + 1000)}` });
    } catch {
      setRecords(DEMO_RECORDS);
      setPatientInfo({ name: searchQuery, id: 'P1001' });
    }
    setLoading(false);
  };

  const handleAddPrescriptionRow = () => {
    setNewVisit((v) => ({
      ...v,
      prescriptions: [...v.prescriptions, { medicine: '', dosage: '' }],
    }));
  };

  const handlePrescriptionChange = (i, field, value) => {
    setNewVisit((v) => {
      const updated = [...v.prescriptions];
      updated[i][field] = value;
      return { ...v, prescriptions: updated };
    });
  };

  const handleCreateRecord = async (e) => {
    e.preventDefault();
    try {
      await createRecord({ ...newVisit, patientUserId: searchQuery });
      setRecords((prev) => [{ ...newVisit, _id: Date.now().toString(), visitDate: new Date().toISOString() }, ...prev]);
      setShowNewVisit(false);
      setNewVisit({ visitNotes: '', diagnosis: '', prescriptions: [{ medicine: '', dosage: '' }] });
    } catch {
      setRecords((prev) => [{ ...newVisit, _id: Date.now().toString(), visitDate: new Date().toISOString() }, ...prev]);
      setShowNewVisit(false);
    }
  };

  // EXTRA FEATURE - Download prescription as text file
  const downloadPrescription = (record) => {
    const content = [
      '===== PRESCRIPTION =====',
      `Date: ${new Date(record.visitDate).toLocaleDateString()}`,
      `Diagnosis: ${record.diagnosis}`,
      '',
      'MEDICINES:',
      ...record.prescriptions.map((p, i) => `${i + 1}. ${p.medicine} — ${p.dosage}`),
      '',
      'Visit Notes:',
      record.visitNotes,
      '',
      'Generated by HealthCare Pro',
    ].join('\n');

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `prescription_${new Date(record.visitDate).toLocaleDateString('en-GB').replace(/\//g, '-')}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div>
      <h1 className="page-title">📁 Patient Records</h1>

      {/* Search */}
      <div className="card">
        <h3 className="section-title">🔍 Search Patient</h3>
        <div style={{ display: 'flex', gap: '8px' }}>
          <input
            type="text"
            className="form-control"
            placeholder="Patient name or ID..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
          />
          <button className="btn btn-primary" onClick={handleSearch} disabled={loading}>
            {loading ? '⏳' : '🔍 Search'}
          </button>
        </div>
      </div>

      {/* Patient Profile Summary */}
      {patientInfo && (
        <div className="card fade-in" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <div style={{ fontWeight: '700', fontSize: '18px' }}>👤 {patientInfo.name}</div>
            <div style={{ color: 'var(--text-secondary)', fontSize: '13px' }}>Patient ID: {patientInfo.id}</div>
          </div>
          <button className="btn btn-primary" onClick={() => setShowNewVisit(true)}>
            ➕ New Visit Note
          </button>
        </div>
      )}

      {/* New Visit Form */}
      {showNewVisit && (
        <div className="card fade-in">
          <h3 className="section-title">📝 New Visit Note</h3>
          <form onSubmit={handleCreateRecord}>
            <div className="form-group">
              <label>Diagnosis *</label>
              <input
                type="text"
                className="form-control"
                value={newVisit.diagnosis}
                onChange={(e) => setNewVisit({ ...newVisit, diagnosis: e.target.value })}
                required
                placeholder="e.g. Upper Respiratory Infection"
              />
            </div>
            <div className="form-group">
              <label>Visit Notes</label>
              <textarea
                className="form-control"
                rows={3}
                value={newVisit.visitNotes}
                onChange={(e) => setNewVisit({ ...newVisit, visitNotes: e.target.value })}
                placeholder="Patient's complaint, observations, recommendations..."
              />
            </div>
            <div className="form-group">
              <label>Prescriptions</label>
              {newVisit.prescriptions.map((p, i) => (
                <div key={i} style={{ display: 'flex', gap: '8px', marginBottom: '8px' }}>
                  <input
                    type="text"
                    className="form-control"
                    placeholder="Medicine name & dosage"
                    value={p.medicine}
                    onChange={(e) => handlePrescriptionChange(i, 'medicine', e.target.value)}
                  />
                  <input
                    type="text"
                    className="form-control"
                    placeholder="Frequency (e.g. twice daily)"
                    value={p.dosage}
                    onChange={(e) => handlePrescriptionChange(i, 'dosage', e.target.value)}
                  />
                </div>
              ))}
              <button type="button" className="btn btn-outline btn-sm" onClick={handleAddPrescriptionRow}>
                ➕ Add Medicine
              </button>
            </div>
            <div style={{ display: 'flex', gap: '8px' }}>
              <button type="submit" className="btn btn-primary">💾 Save Visit</button>
              <button type="button" className="btn btn-outline" onClick={() => setShowNewVisit(false)}>Cancel</button>
            </div>
          </form>
        </div>
      )}

      {/* Records List */}
      {searched && (
        <div>
          {records.length === 0 ? (
            <div className="card" style={{ textAlign: 'center', padding: '40px' }}>
              <p style={{ color: 'var(--text-secondary)' }}>No records found for this patient.</p>
            </div>
          ) : (
            records.map((rec) => (
              <div key={rec._id} className="card fade-in">
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                  <div>
                    <div style={{ fontWeight: '700', fontSize: '16px' }}>{rec.diagnosis}</div>
                    <div style={{ color: 'var(--text-secondary)', fontSize: '13px', marginTop: '2px' }}>
                      📅 {new Date(rec.visitDate).toLocaleDateString()}
                    </div>
                  </div>
                  <div style={{ display: 'flex', gap: '6px' }}>
                    <button
                      className="btn btn-outline btn-sm"
                      onClick={() => setSelectedRecord(selectedRecord?._id === rec._id ? null : rec)}
                    >
                      {selectedRecord?._id === rec._id ? 'Hide' : '👁 View'}
                    </button>
                    <button
                      className="btn btn-primary btn-sm"
                      onClick={() => downloadPrescription(rec)}
                    >
                      ⬇️ Rx
                    </button>
                  </div>
                </div>

                {selectedRecord?._id === rec._id && (
                  <div style={{ marginTop: '16px', borderTop: '1px solid var(--border)', paddingTop: '16px' }} className="fade-in">
                    <p style={{ marginBottom: '8px', fontSize: '14px' }}>
                      <strong>Visit Notes:</strong> {rec.visitNotes}
                    </p>
                    {rec.prescriptions?.length > 0 && (
                      <div>
                        <strong style={{ fontSize: '14px' }}>💊 Prescriptions:</strong>
                        <ul style={{ paddingLeft: '20px', marginTop: '6px' }}>
                          {rec.prescriptions.map((p, i) => (
                            <li key={i} style={{ fontSize: '13px', color: 'var(--text)', marginBottom: '4px' }}>
                              <strong>{p.medicine}</strong> — {p.dosage}
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}
                  </div>
                )}
              </div>
            ))
          )}
        </div>
      )}
    </div>
  );
};

export default PatientRecords;
